"""empty message

Revision ID: 2c8f4ccbf873
Revises: f6018d669f5a
Create Date: 2018-03-23 12:35:59.693540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c8f4ccbf873'
down_revision = 'f6018d669f5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog_post', sa.Column('author_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'blog_post', 'user', ['author_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'blog_post', type_='foreignkey')
    op.drop_column('blog_post', 'author_id')
    # ### end Alembic commands ###
